# Generated by Django 3.2.8 on 2021-10-17 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posts/')),
                ('image_name', models.CharField(max_length=60)),
                ('image_caption', models.CharField(max_length=300)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('image_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='insta.profile')),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
