# Generated by Django 3.2.8 on 2021-10-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='comments',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
